### ISSUE TITLE
Move plugin source to https://github.com/gpc

### ISSUE THREAD

**Issue by graemerocher** [nwwells/grails-export#9]
Being a popular plugin, can we move the source to https://github.com/gpc ?

The GPC is an organisation where prominent plugin maintainers can contribute to help make sure the plugin stays up-to-date

**Comment by nwwells** [comment]
I have no problem with that. Note that I'm not the original plugin author. Andreas Schmitt gets the props there. His email: andreas DOT schmitt DOT mi AT gmail. Is there anything I need to do to transfer it? I haven't been able to work on it as much as I should, since I've transitioned to mostly client-side work.

**Comment by graemerocher** [comment]
I'll just fork it over to the GPC and add commits rights for you in case you do want to work on it again

**Comment by graemerocher** [comment]
It is now at https://github.com/gpc/grails-export, I have granted you permission to write to that repo. You could modify this repo pointing people to https://github.com/gpc/grails-export
